<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LkeKriteriaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('lke_kriteria')->insert([
            ['id' => 1,  'komponen_id' => 11, 'nomor' => 1,  'uraian' => 'Terdapat pedoman teknis perencanaan kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 2,  'komponen_id' => 11, 'nomor' => 2,  'uraian' => 'Terdapat dokumen perencanaan kinerja jangka panjang', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 3,  'komponen_id' => 11, 'nomor' => 3,  'uraian' => 'Terdapat dokumen perencanaan kinerja jangka menengah', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 4,  'komponen_id' => 11, 'nomor' => 4,  'uraian' => 'Terdapat dokumen perencanaan kinerja jangka pendek', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 5,  'komponen_id' => 11, 'nomor' => 5,  'uraian' => 'Terdapat dokumen perencanaan aktivitas yang mendukung kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 6,  'komponen_id' => 11, 'nomor' => 6,  'uraian' => 'Terdapat dokumen perencanaan anggaran yang mendukung kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 7,  'komponen_id' => 12, 'nomor' => 1,  'uraian' => 'Dokumen Perencanaan Kinerja telah diformalkan', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 8,  'komponen_id' => 12, 'nomor' => 2,  'uraian' => 'Dokumen Perencanaan Kinerja telah dipublikasikan tepat waktu', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 9,  'komponen_id' => 12, 'nomor' => 3,  'uraian' => 'Dokumen Perencanaan Kinerja telah menggambarkan kebutuhan atas kinerja sebenarnya', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 10, 'komponen_id' => 12, 'nomor' => 4,  'uraian' => 'Kualitas Rumusan Hasil (Tujuan/Sasaran) telah jelas menggambarkan kondisi kinerja yang akan dicapai', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 11, 'komponen_id' => 12, 'nomor' => 5,  'uraian' => 'Ukuran Keberhasilan (Indikator Kinerja) telah memenuhi kriteria SMART', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 12, 'komponen_id' => 12, 'nomor' => 6,  'uraian' => 'Indikator Kinerja Utama (IKU) telah menggambarkan kondisi Kinerja Utama yang harus dicapai', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 13, 'komponen_id' => 12, 'nomor' => 7,  'uraian' => 'Target yang telah ditetapkan dalam perencanaan kinerja dapat dicapai (achievable), menantang, dan realistis', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 14, 'komponen_id' => 12, 'nomor' => 8,  'uraian' => 'Setiap Dokumen Perencanaan Kinerja menggambarkan hubungan yang berkesinambungan (Cascading)', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 15, 'komponen_id' => 12, 'nomor' => 9,  'uraian' => 'Perencanaan kinerja dapat memberikan informasi tentang hubungan kinerja antar bidang (Crosscutting)', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 16, 'komponen_id' => 13, 'nomor' => 1,  'uraian' => 'Anggaran yang ditetapkan telah mengacu pada Kinerja yang ingin dicapai', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 17, 'komponen_id' => 13, 'nomor' => 2,  'uraian' => 'Aktivitas yang dilaksanakan telah mendukung Kinerja yang ingin dicapai', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 18, 'komponen_id' => 13, 'nomor' => 3,  'uraian' => 'Target yang ditetapkan dalam Perencanaan Kinerja telah dicapai dengan baik, atau setidaknya masih on the right track', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 19, 'komponen_id' => 13, 'nomor' => 4,  'uraian' => 'Rencana aksi kinerja dapat berjalan dinamis karena capaian kinerja selalu dipantau secara berkala', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 20, 'komponen_id' => 13, 'nomor' => 5,  'uraian' => 'Terdapat perbaikan/penyempurnaan Dokumen Perencanaan Kinerja dari hasil analisis perbaikan kinerja sebelumnya', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 21, 'komponen_id' => 21, 'nomor' => 1,  'uraian' => 'Terdapat pedoman teknis pengukuran kinerja dan pengumpulan data kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 22, 'komponen_id' => 21, 'nomor' => 2,  'uraian' => 'Terdapat Definisi Operasional yang jelas atas kinerja dan cara mengukur indikator kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 23, 'komponen_id' => 21, 'nomor' => 3,  'uraian' => 'Terdapat mekanisme yang jelas terhadap pengumpulan data kinerja yang dapat diandalkan', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 24, 'komponen_id' => 22, 'nomor' => 1,  'uraian' => 'Pimpinan selalu terlibat sebagai pengambil keputusan (Decision Maker) dalam mengukur capaian kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 25, 'komponen_id' => 22, 'nomor' => 2,  'uraian' => 'Data kinerja yang dikumpulkan telah relevan untuk mengukur capaian kinerja yang diharapkan', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 26, 'komponen_id' => 22, 'nomor' => 3,  'uraian' => 'Data kinerja yang dikumpulkan telah relevan untuk mengukur capaian kinerja yang diharapkan', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 27, 'komponen_id' => 22, 'nomor' => 4,  'uraian' => 'Pengukuran kinerja telah dilakukan secara berkala', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 28, 'komponen_id' => 22, 'nomor' => 5,  'uraian' => 'Setiap level organisasi melakukan pemantauan atas pengukuran capaian kinerja unit dibawahnya', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 29, 'komponen_id' => 22, 'nomor' => 6,  'uraian' => 'Pengumpulan data kinerja telah memanfaatkan Teknologi Informasi (Aplikasi)', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 30, 'komponen_id' => 22, 'nomor' => 7,  'uraian' => 'Pengukuran capaian kinerja telah memanfaatkan Teknologi Informasi (Aplikasi)', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 31, 'komponen_id' => 23, 'nomor' => 1,  'uraian' => 'Pengukuran Kinerja telah menjadi dasar dalam penyesuaian tunjangan kinerja / penghasilan', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 32, 'komponen_id' => 23, 'nomor' => 2,  'uraian' => 'Pengukuran Kinerja telah menjadi dasar dalam penempatan/penghapusan Jabatan struktural maupun fungsional', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 33, 'komponen_id' => 23, 'nomor' => 3,  'uraian' => 'Pengukuran kinerja telah mempengaruhi penyesuaian (Refocusing) Organisasi', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 34, 'komponen_id' => 23, 'nomor' => 4,  'uraian' => 'Pengukuran kinerja telah mempengaruhi penyesuaian Strategi dalam mencapai kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 35, 'komponen_id' => 23, 'nomor' => 5,  'uraian' => 'Pengukuran kinerja telah mempengaruhi penyesuaian kebijakan dalam mencapai kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 36, 'komponen_id' => 23, 'nomor' => 6,  'uraian' => 'Pengukuran kinerja telah mempengaruhi penyesuaian Aktivitas dalam mencapai kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 37, 'komponen_id' => 23, 'nomor' => 7,  'uraian' => 'Pengukuran kinerja telah mempengaruhi penyesuaian Anggaran dalam mencapai kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 38, 'komponen_id' => 23, 'nomor' => 8,  'uraian' => 'Terdapat efisiensi atas penggunaan anggaran dalam mencapai kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 39, 'komponen_id' => 31, 'nomor' => 1,  'uraian' => 'Dokumen Laporan Kinerja telah disusun', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 40, 'komponen_id' => 31, 'nomor' => 2,  'uraian' => 'Dokumen Laporan Kinerja telah disusun secara berkala', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 41, 'komponen_id' => 31, 'nomor' => 3,  'uraian' => 'Dokumen Laporan Kinerja telah diformalkan', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 42, 'komponen_id' => 32, 'nomor' => 1,  'uraian' => 'Dokumen Laporan Kinerja disusun secara berkualitas sesuai dengan standar', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 43, 'komponen_id' => 32, 'nomor' => 2,  'uraian' => 'Dokumen Laporan Kinerja telah mengungkap seluruh informasi tentang pencapaian kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 44, 'komponen_id' => 32, 'nomor' => 3,  'uraian' => 'Dokumen Laporan Kinerja telah menginformasikan perbandingan realisasi kinerja dengan target tahunan', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 45, 'komponen_id' => 32, 'nomor' => 4,  'uraian' => 'Dokumen Laporan Kinerja telah menginformasikan perbandingan realisasi kinerja dengan target jangka menengah', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 46, 'komponen_id' => 32, 'nomor' => 5,  'uraian' => 'Dokumen Laporan Kinerja telah menginformasikan perbandingan realisasi kinerja dengan realisasi kinerja tahun-tahun sebelumnya', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 47, 'komponen_id' => 32, 'nomor' => 6,  'uraian' => 'Dokumen Laporan Kinerja telah menginformasikan perbandingan realisasi kinerja dengan realisasi kinerja di level nasional/internasional', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 48, 'komponen_id' => 32, 'nomor' => 7,  'uraian' => 'Dokumen Laporan Kinerja telah menginfokan kualitas atas capaian kinerja beserta upaya nyata dan/atau hambatannya', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 49, 'komponen_id' => 32, 'nomor' => 8,  'uraian' => 'Dokumen Laporan Kinerja telah menginfokan efisiensi atas penggunaan sumber daya dalam mencapai kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 50, 'komponen_id' => 32, 'nomor' => 9,  'uraian' => 'Dokumen Laporan Kinerja telah menginfokan upaya perbaikan dan penyempurnaan kinerja ke depan', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 51, 'komponen_id' => 33, 'nomor' => 1,  'uraian' => 'Informasi dalam laporan kinerja selalu menjadi perhatian utama pimpinan (Bertanggung Jawab)', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 52, 'komponen_id' => 33, 'nomor' => 2,  'uraian' => 'Penyajian informasi dalam laporan kinerja menjadi kepedulian seluruh pegawai', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 53, 'komponen_id' => 33, 'nomor' => 3,  'uraian' => 'Informasi dalam laporan kinerja berkala telah digunakan dalam penyesuaian aktivitas untuk mencapai kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 54, 'komponen_id' => 33, 'nomor' => 4,  'uraian' => 'Informasi dalam laporan kinerja berkala telah digunakan dalam penyesuaian penggunaan anggaran untuk mencapai kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 55, 'komponen_id' => 33, 'nomor' => 5,  'uraian' => 'Informasi dalam laporan kinerja telah digunakan dalam evaluasi pencapaian keberhasilan kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 56, 'komponen_id' => 33, 'nomor' => 6,  'uraian' => 'Informasi dalam laporan kinerja berkala telah digunakan dalam penyesuaian perencanaan kinerja yang akan dihadapi berikutnya', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 57, 'komponen_id' => 33, 'nomor' => 7,  'uraian' => 'Informasi dalam laporan kinerja selalu mempengaruhi perubahan budaya kinerja organisasi', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 58, 'komponen_id' => 41, 'nomor' => 1,  'uraian' => 'Terdapat pedoman teknis Evaluasi Akuntabilitas Kinerja Instansi Pemerintah (AKIP) Internal', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 59, 'komponen_id' => 41, 'nomor' => 2,  'uraian' => 'Evaluasi Akuntabilitas Kinerja Instansi Pemerintah (AKIP) Internal telah dilaksanakan pada seluruh unit kerja/perangkat daerah', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 60, 'komponen_id' => 41, 'nomor' => 3,  'uraian' => 'Evaluasi Akuntabilitas Kinerja Instansi Pemerintah (AKIP) Internal telah dilaksanakan secara berjenjang', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 61, 'komponen_id' => 42, 'nomor' => 1,  'uraian' => 'Evaluasi AKIP Internal telah dilaksanakan sesuai standar', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 62, 'komponen_id' => 42, 'nomor' => 2,  'uraian' => 'Evaluasi AKIP Internal telah dilaksanakan oleh SDM yang memadai', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 63, 'komponen_id' => 42, 'nomor' => 3,  'uraian' => 'Evaluasi AKIP Internal telah dilaksanakan dengan pendalaman yang memadai', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 64, 'komponen_id' => 42, 'nomor' => 4,  'uraian' => 'Evaluasi AKIP Internal telah dilaksanakan pada seluruh unit kerja/perangkat daerah', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 65, 'komponen_id' => 42, 'nomor' => 5,  'uraian' => 'Evaluasi AKIP Internal telah dilaksanakan menggunakan Teknologi Informasi (Aplikasi)', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 66, 'komponen_id' => 43, 'nomor' => 1,  'uraian' => 'Seluruh rekomendasi atas hasil evaluasi AKIP internal telah ditindaklanjuti', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 67, 'komponen_id' => 43, 'nomor' => 2,  'uraian' => 'Telah terjadi peningkatan implementasi SAKIP dengan melaksanakan tindak lanjut atas rekomendasi hasil evaluasi akuntabilitas Kinerja internal', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 68, 'komponen_id' => 43, 'nomor' => 3,  'uraian' => 'Hasil dari Evaluasi Akuntabilitas Kinerja Internal telah dimanfaatkan untuk perbaikan dan peningkatan akuntabilitas kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 69, 'komponen_id' => 43, 'nomor' => 4,  'uraian' => 'Hasil dari Evaluasi Akuntabilitas Kinerja Internal telah dimanfaatkan dalam mendukung efektifitas dan efisiensi kinerja', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 70, 'komponen_id' => 43, 'nomor' => 5,  'uraian' => 'Telah terjadi perbaikan dan peningkatan kinerja dengan memanfaatkan hasil evaluasi akuntablitas kinerja internal', 'created_at' => '2026-03-25 02:30:38'],
            ['id' => 71, 'komponen_id' => 12, 'nomor' => 10, 'uraian' => 'Setiap unit/satuan kerja merumuskan dan menetapkan Perencanaan Kinerja.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 72, 'komponen_id' => 12, 'nomor' => 11, 'uraian' => 'Setiap pegawai merumuskan dan menetapkan Perencanaan Kinerja.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 73, 'komponen_id' => 13, 'nomor' => 6,  'uraian' => 'Terdapat perbaikan/penyempurnaan Dokumen Perencanaan Kinerja dalam mewujudkan kondisi/hasil yang lebih baik.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 74, 'komponen_id' => 13, 'nomor' => 7,  'uraian' => 'Setiap unit/satuan kerja memahami dan peduli, serta berkomitmen dalam mencapai kinerja yang telah direncanakan.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 75, 'komponen_id' => 13, 'nomor' => 8,  'uraian' => 'Setiap Pegawai memahami dan peduli, serta berkomitmen dalam mencapai kinerja yang telah direncanakan.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 76, 'komponen_id' => 23, 'nomor' => 9,  'uraian' => 'Setiap unit/satuan kerja memahami dan peduli atas hasil pengukuran kinerja.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 77, 'komponen_id' => 23, 'nomor' => 10, 'uraian' => 'Setiap pegawai memahami dan peduli atas hasil pengukuran kinerja.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 78, 'komponen_id' => 31, 'nomor' => 4,  'uraian' => 'Dokumen Laporan Kinerja telah direviu.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 79, 'komponen_id' => 31, 'nomor' => 5,  'uraian' => 'Dokumen Laporan Kinerja telah dipublikasikan.', 'created_at' => '2026-03-31 03:35:07'],
            ['id' => 80, 'komponen_id' => 31, 'nomor' => 6,  'uraian' => 'Dokumen Laporan Kinerja telah disampaikan tepat waktu.', 'created_at' => '2026-03-31 03:35:07'],
        ]);
    }
}